//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Nombre_usuario { get; set; }
        public string Password { get; set; }
        public Nullable<int> Id_Rol { get; set; }
        public Nullable<int> Id_Estado { get; set; }
    
        public virtual Estado Estado { get; set; }
        public virtual Rol Rol { get; set; }
    }
}
